export const SOCKET_CONNECT_SUCCESS = "SOCKET_CONNECT_SUCCESS";
export const JOIN_ROOM = "JOIN_ROOM";
export const SWITCH_ROOM = "SWITCH_ROOM";
export const UPDATE_HISTORY = "UPDATE_HISTORY";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
